services:
  - type: web
    name: mindx-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_PATH
        value: /var/data/mindx.db
    disk:
      name: mindx-data
      mountPath: /var/data
      sizeGB: 1

# redeploy 2026-04-10T12:06:17.295Z
